config/routes.rb
Rails.application.routes.draw do

  
  root :to => "main#welcome"
  
  post "/conversion", :to => "main#conversion"
  get "/stats", :to => "main#stats"
  get "/:key", :to => "keys#show", :as => :key
end

app/models/conversion.rb
class Conversion < ActiveRecord::Base
    require 'fileutils'
    belongs_to :key
    mount_uploader :original_file, MediaUploader
    validates :original_file, :presence => true
    validates :key, :presence => true, :uniqueness => true
    validates :convtype, :presence => true, :inclusion => {:in => [:audio, :video]}
    validates :mode, :presence => true, :inclusion => {:in => [:concurrent, :sequential]}
    validates :status, :presence => true, :inclusion => {:in => [:new, :processing, :completed, :failed]}
    validates :percentage, :presence => true, :numericality => {:greater_than_or_equal_to => 0, :less_than_or_equal_to => 100}
    
    scope :not_completed, -> {where(status: [:new, :processing])}
    scope :processing, -> {where(status: :processing)}
    scope :completed, -> {where(status: :completed)}
    scope :failed, -> {where(status: :failed)}
    
    before_destroy :destroy_related_files
    
    def self.find_by_key key
        k = Key.where(keystring: key)
        Conversion.where(key: k).first
    end
    
    def format_percentage
        percentage.to_s + " %"
    end
    
    def to_json_status
        [status, percentage].to_json
    end
    
    def zipurl hostname
        str = zippath
        str[Rails.root.to_s] = ""
        str["/public"] = hostname
        str
    end
    
    def convtype
        read_attribute(:convtype).try(:to_sym)
    end
    
    def mode
        read_attribute(:mode).try(:to_sym)
    end
    
    def status
        read_attribute(:status).try(:to_sym)
    end
    
    private
    
    def destroy_related_files
        remove_original_file!
        FileUtils.rm_r("#{Rails.root}/public/uploads/conversion/original_file/#{key.to_s}")
        if zippath
            FileUtils.rm(zippath)
        end
        # Just in case it is from before it all worked correctly
        if File.exists?("#{Rails.root}/public/conversions/#{key.to_s}")
            FileUtils.rm_r("#{Rails.root}/public/conversions/#{key.to_s}")
        end
    end
end

app/models/key.rb
class Key < ActiveRecord::Base
    has_one :conversion
    validates :keystring, :presence => true, :length => {:is => 20}, :uniqueness => true
    
    def self.generate
        k = self.new
        k.keystring = Forgery(:basic).text(:exactly => 20)
        while !k.save
            k.keystring = Forgery(:basic).text(:exactly => 20)
        end
        k
    end
    
    def to_s
        self.keystring
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'sys/filesystem'
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :load_stats
  
  def render_error error
    if error.to_s == "forbidden"
      render "errors/forbidden", :status => :forbidden, :layout => "error" and return
    elsif error.to_s == "notfound"
      render "errors/notfound", :status => :not_found, :layout => "error" and return
    end
  end
  
  protected
  
  def load_stats
     @processing_count = Conversion.processing.count
     diskstat = Sys::Filesystem.stat("#{Rails.root}/public/")
     @available_disk_space = ((diskstat.block_size * diskstat.blocks_available).to_f/1024/1024/1024).round(2)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
	layout :error
	
	def notfound
	end
	
	def forbidden
	end
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
    
  before_filter :find_object
    
  def show
      respond_to do |format|
          format.html
          format.json do
              render :json => @obj.to_json_status
          end
      end
  end
  
  private
  
  def find_object
      @obj = Conversion.find_by_key(params[:key])
      if @obj.nil?
          render_error :notfound
      end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def blank
    end
    
    def welcome
    end
    
    def conversion
        @conv = Conversion.new
        @conv.key = Key.generate
        @conv.original_file = params[:original_file]
        @conv.convtype = params[:type].to_sym
        @conv.mode = params[:processing].to_sym
        @conv.status = :new
        @conv.percentage = 0
        if !@conv.save
            @conv.key.destroy
            flash[:error] = "Conversion could not be started: #{@conv.errors.messages.to_s}. Please try again."
            redirect_to root_path
        end
        ConversionWorker.perform_async(@conv.key.to_s)
    end
    
    def stats
        respond_to do |format|
            format.json do
               load_stats
               render :json => [@processing_count, @available_disk_space].to_json 
            end
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_hostname
        request.protocol + request.host + request.port_string
    end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/helpers/main_helper.rb
module MainHelper
    def conversion_types_for_select
        [["Audio", :audio], ["Video", :video]]
    end
    
    def processing_types_for_select
        [["Concurrent (may significantly slow down the server)", :concurrent], ["Sequential (may take longer)", :sequential]]
    end
end

app/views/keys/_completed.html.haml
= content_for :summary do
  %p Your file has been converted successfully. You can download the ZIP package below or save the link to download it later. The package will stay on the server for 7 days, then it will be automatically deleted.
%h1.success Conversion successful!
.downloadbutton
  = button_to "Download the ZIP package", obj.zipurl(current_hostname), method: :get
.convkey
  Unique conversion key:
  = obj.key.to_s
.link
  = link_to "Save this link to download the package later", key_path(obj.key.to_s)
= content_for :additional do
  %p If you want to build such conversion into your own Rails application, check out the rff Ruby gem this converter is based on!

app/views/keys/_failed.html.haml
= content_for :summary do
  %p Sorry, your conversion has failed. This can be either a bug in rff Ruby gem, FFmpeg itself or temporary server problem. If it is a bug with rff I can probably diagnose and fix it. Please send an e-mail to phitherek [at] gmail [dot] com with the conversion key below.
%h1.failed Something went wrong :(
.convkey
  Unique conversion key:
  = obj.key.to_s
= content_for :additional do
  %p Sorry for any inconvenience. Your feedback can make the rff Ruby gem and RFF Converter better!

app/views/keys/_not_completed.html.haml
= content_for :summary do
  %p Your conversion has not completed. This can mean two things - either it is still running and you have to wait until it finishes or there was a bug with your particular file and RFF Converter engine crashed not changing the status of this conversion. In second case (if the success or failure page does not appear for a very long time) please e-mail the below conversion key to phitherek [at] gmail [dot] com and I will try to inspect that.
%h1.not_completed Conversion not completed...
.convkey
  Unique conversion key:
  = obj.key.to_s
= content_for :additional do
  %p Sorry for any inconvenience. Your feedback can make the rff Ruby gem and RFF Converter better!

app/views/keys/show.html.haml
- if @obj.status == :completed
  = render :partial => "completed", :locals => {obj: @obj}
- elsif @obj.status == :new || @obj.status == :processing
  = render :partial => "not_completed", :locals => {obj: @obj}
- else
  = render :partial => "failed", :locals => {obj: @obj}

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title RFF Converter
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .header
      = image_tag "rff-converter-logo.png"
    .flashes
      .notice
        = flash[:notice]
      .error
        = flash[:error]
    .summary
      = yield :summary
    .formbox
      = yield
    .additional
      = yield :additional
    .stats
      %p
        Currently processing:
        %span#processing_count= @processing_count
        conversion(s). Too many conversions at once can kill the server. If there are a few currently processing please consider running your conversion later.
      %p
        Available disk space: 
        %span#available_disk_space= @available_disk_space
        GB. Your conversion will not complete if there is not enough disk space. Old conversions are removed from server after 7 days (cleanup process runs every 10 minutes), please check back later if there is not enough disk space now.
    .footer
      .line
        RFF Converter &copy; 2014 by Phitherek_
      .line
        Powered by
        = link_to "rff", "https://rubygems.org/gems/rff"
        Ruby gem &copy; 2014 by Phitherek_
      .line
        Powered by
        = link_to "Ruby on Rails", "http://www.rubyonrails.org"

app/views/layouts/error.html.haml
!!! 5
%html
  %head
    %title Something went wrong... - RFF Converter
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .header
      = image_tag "rff-converter-logo.png"
    .error
      = yield
    .footer
      .line
        RFF Converter &copy; 2014 by Phitherek_
      .line
        Powered by
        = link_to "rff", "https://rubygems.org/gems/rff"
        Ruby gem &copy; 2014 by Phitherek_
      .line
        Powered by
        = link_to "Ruby on Rails", "http://www.rubyonrails.org"

app/views/main/_progressbar.html.haml
.pbcontainer{:class => barclass}
  .progress
    .bar{:style => "width: 0%;"}
  .progress_percentage
    0%

app/views/main/blank.html.haml
= content_for :summary do
  %p A blank test file - summary
%p Blank content
= content_for :additional do
  %p Additional blank

app/views/main/conversion.html.haml
= content_for :summary do
  %p Your file is now being converted. When the conversion succeeds you will have an option to download the converted files as a ZIP package. This package will stay on the server for 7 days and then will be automatically deleted.
%h1#form_title Please wait, conversion in progress...
= render partial: "main/progressbar", locals: {barclass: "conversion"}
= content_for :additional do
  %p NOTICE: As FFmpeg does not provide percentage information, the percentage is calculated by rff Ruby gem based on the duration of input file and current time position from conversion status information. If either is missing or not available the percentage displayed and the progress bar will not be accurate but that does NOT necessarily mean that the conversion process hung or died. Please be patient as the conversion process might take a long time to complete.
  = form_tag(key_path(@conv.key.to_s), id: :afterconversion_form, data: {key: @conv.key.to_s}, method: :get)

app/views/main/welcome.html.haml
= content_for :summary do
  %p Welcome to RFF Converter, a Ruby on Rails based most-to-HTML5 media converter. Just use the form below to upload an audio or video file and this converter will - sequentially or concurrently, depending on your choice - convert it to OGG, WAV and MP3 formats (if it' s an audio file) or OGV, MP4 and WEBM formats (if it' s a video file). If the conversion succeeds it will provide a ZIP package with converted files - then you can use them to source an audio or video element on your HTML5 page.
%h1#form_title Input your file to begin the conversion:
.form_space
  = form_tag(conversion_path, multipart: true) do
    .formrow  
      = label_tag :type, "File type:"
      = select_tag :type, options_for_select(conversion_types_for_select)
    .formrow
      = label_tag :processing, "Processing mode:"
      = select_tag :processing, options_for_select(processing_types_for_select)
    .formrow
      = label_tag :original_file, "Select file:"
      = file_field_tag :original_file
    .formrow
      = token_tag
      = submit_tag "Begin"
.upload_message